config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
  resources :users
  resources :products do
    resources :images, only: [:create]
  end
  root 'admin#index'
end


  root "products#index"
  get '/home/index'
  devise_for :users

  resources :line_items, only: [:create, :update, :destroy]
  resources :facturations, only: [:show, :index]
  resources :baskets, only: [:create, :update, :destroy, :show]
  resources :charges
  resources :categories, only: [:create, :update, :destroy, :show, :index]
  resources :products
end

app/models/basket.rb
class Basket < ApplicationRecord
  belongs_to :user, optional: true
  has_one :facturation
  has_many :line_items, dependent: :destroy

  def add_product(product)
		item = line_items.find_by(product: product)

		if item
			item.quantity += 1
		else
			item = line_items.new(product: product)
		end
		item
	end

end

app/controllers/baskets_controller.rb
class BasketsController < ApplicationController
  include BasketsHelper
  before_action :set_price

  def index

  end


  def show
    unless @current_basket.id == Basket.find(params[:id]).id
      redirect_to root_path
    end
  end


  def new

  end


  def edit
    
  end


  def create

  end


  def update

  end


  def destroy

  end

end

app/helpers/baskets_helper.rb
module BasketsHelper
  def set_price
    @price = 0
    @current_basket.line_items.each do |item|
      @price += (item.product.price * item.quantity)
    end
    @price = @price.round(2)
  end
end

app/views/baskets/_button.html.erb
<% if @price != 0 %>
  <td colspan="3" class="text-right">
    <%= link_to new_charge_path do %>
      <button type="button" rel="tooltip" class="btn btn-info btn-round btn-dribbble" id="checkout-btn">
          Finaliser l'achatte
          <i class="now-ui-icons arrows-1_minimal-right"></i>
      </button>
    <% end %>
  </td>
<% end %>

app/views/baskets/_form.html.erb
<%= form_with(model: basket, local: true) do |form| %>
  <% if basket.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(basket.errors.count, "error") %> prohibited this basket from being saved:</h2>

      <ul>
      <% basket.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :quantity %>
    <%= form.number_field :quantity %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/baskets/edit.html.erb
<h1>Editing Basket</h1>

<%= render 'form', basket: @basket %>

<%= link_to 'Show', @basket %> |
<%= link_to 'Back', baskets_path %>

app/views/baskets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Baskets</h1>

<table>
  <thead>
    <tr>
      <th>Quantity</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @baskets.each do |basket| %>
      <tr>
        <td><%= basket.quantity %></td>
        <td><%= link_to 'Show', basket %></td>
        <td><%= link_to 'Edit', edit_basket_path(basket) %></td>
        <td><%= link_to 'Destroy', basket, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Basket', new_basket_path %>

app/views/baskets/new.html.erb
<h1>New Basket</h1>

<%= render 'form', basket: @basket %>

<%= link_to 'Back', baskets_path %>

app/views/baskets/show.html.erb
<p id="notice"><%= notice %></p>

<div class="container mt-5">
  <div class="row">
    <div class="col-md-12">
      <br/>
    </div>
    <div class="col-md-12">
        <div class="card card-plain">
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table table-shopping">
                        <thead class="">
                            <th class="text-center">
                            </th>
                            <th>
                                Produit
                            </th>
                            <th>
                                Marque
                            </th>
                            <th class="text-right">
                                Prix
                            </th>
                            <th class="text-right">
                                Quantité
                            </th>
                            <th class="text-right">
                                Montant
                            </th>
                        </thead>
                        <tbody>
                          <% @current_basket.line_items.each do |item| %>
                            <tr id="item_fulldiv_<%= item.id %>">
                                <td>
                                    <div class="img-container">
                                        <img src="http://www.kittycatconnection.org/uploads/1/6/8/9/16894946/header_images/1532312571.jpg" alt="...">
                                    </div>
                                </td>
                                <td class="td-name">
                                    <a href="/products/<%= item.product.id %>"><%= item.product.title %></a>
                                    <br />
                                    <small>Réf : <%= item.product.reference %></small>
                                </td>
                                <td>
                                    <%= item.product.brand %>
                                </td>
                                <td class="td-number">
                                    <%= item.product.price %><small>€</small>
                                </td>

                                <td class="td-number">

                                    <div class="btn-group btn-group-basket">
                                      <%= link_to line_item_path(item.id, :operator => "reduce"), method: :PUT, remote: true do %>
                                        <button class="btn btn-info btn-sm btn-round btn-dribbble mr-2">
                                          <i class="now-ui-icons ui-1_simple-delete"></i>
                                        </button>
                                      <% end %>
                                      <div id="item_quantity_<%= item.id%>">
                                          <%= item.quantity %>
                                      </div>
                                        <%= link_to line_item_path(item.id, :operator => "add"), method: :PUT, remote: true do %>
                                          <button  class="btn btn-info btn-sm btn-round btn-dribbble ml-2">
                                              <i class="now-ui-icons ui-1_simple-add"></i>
                                          </button>
                                        <% end %>
                                <td class="td-number" id="item_total_<%= item.id %>">
                                    <%= (item.product.price * item.quantity).round(2) %><small>€</small>
                                </td>
                                <td class="td-actions">
                                  <%= link_to line_item_path(item.id), method: :DELETE, data: {confirm: 'Voulez-vous vraiment supprimer ' + item.product.title} do %>
                                    <button type="button" rel="tooltip" data-placement="left" title="Remove item" class="btn btn-neutral">
                                        <i class="now-ui-icons ui-1_simple-remove"></i>
                                    </button>
                                    <% end %>
                                </td>
                            </tr>
                          <% end %>
                            <tr>
                                <td colspan="3">
                                </td>
                                <td class="td-total">
                                    Total
                                </td>
                                <td class="td-price" id="total_price">
                                    <%= @price.round(2) %><small>€</small>
                                </td>
                                <%= render 'button' %>
                                <p><%= link_to "Retour aux produits", products_path, class: 'text-primary' %></p>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
  </div>
</div>