config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
  resources :users
  resources :products do
    resources :images, only: [:create]
  end
  root 'admin#index'
end


  root "products#index"
  get '/home/index'
  devise_for :users

  resources :line_items, only: [:create, :update, :destroy]
  resources :facturations, only: [:show, :index]
  resources :baskets, only: [:create, :update, :destroy, :show]
  resources :charges
  resources :categories, only: [:create, :update, :destroy, :show, :index]
  resources :products
end

app/models/product.rb
class Product < ApplicationRecord
  has_one_attached :image
  has_many :line_items, dependent: :nullify
  has_many :product_categories
  has_many :categories, through: :product_categories

  validates :title,
    presence: true,
    length: { in: 3..140 }

  validates :price,
    presence: true,
    numericality: { greater_than: 0, less_than: 1001 }

  validates :description,
    presence: true,
    length: { in: 10..1000 }

  validates_length_of :description,
   :minimum   => 10,
   :maximum   => 1000,
   :too_short => "must have at least 20 characters",
   :too_long  => "must have at most 1000 characters"

end

app/controllers/admin/helpers/products_helper.rb
module AdminProductsHelper

  def set_cats
    @all_cat_categories = @product.categories # toutes les catégories auxquelles le chat appartient
    puts "set_cats" * 30
    puts @all_cat_categories
    puts "set_cats" * 30

    @the_cats = []

    @all_cat_categories.each do |category|
      cats = category.products # tout les chats appartenant à la catégorie de la boucle
      cats.each do |cat|
        @the_cats << cat
      end
    end
    puts @the_cats
  end
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < AdminController


  # Methods omitted
  def index

    puts "$" * 60
    puts "PRODUCT ADMIN INDEX"
    puts params
    puts "$" * 60
    @products = Product.all
    @categories = Category.all

  end

  def show

    def set_cats
      
      @all_cat_categories = @product.categories # toutes les catégories auxquelles le chat appartient
      puts "set_cats" * 30
      puts @all_cat_categories
      puts "set_cats" * 30

      @the_cats = []

      @all_cat_categories.each do |category|
        cats = category.products # tout les chats appartenant à la catégorie de la boucle
        cats.each do |cat|
          @the_cats << cat
        end
      end
      puts @the_cats
    end

    @product = Product.find(params[:id])
    @all_product = Product.all
    puts @product.categories
    puts "@product.categories" * 30
    set_cats

    puts "SHOW" * 30



  end






end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  include ProductsHelper



  # GET /products
  # GET /products.json
  def index
    @products = Product.all
    @categories = Category.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
    @product = Product.find(params[:id])
    @all_product = Product.all
    puts @product.categories
    puts "@product.categories" * 30
    set_cats

    puts "SHOW" * 30

  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:title, :description, :price, :quantity, :reference)
    end
end

app/helpers/products_helper.rb
module ProductsHelper

  def set_cats
    @all_cat_categories = @product.categories # toutes les catégories auxquelles le chat appartient
    puts "set_cats" * 30
    puts @all_cat_categories
    puts "set_cats" * 30

    @the_cats = []

    @all_cat_categories.each do |category|
      cats = category.products # tout les chats appartenant à la catégorie de la boucle
      cats.each do |cat|
        @the_cats << cat
      end
    end
    puts @the_cats
  end


end

app/views/admin/products/index.html.erb
<p id="notice"><%= notice %></p>

<div class="main">

  <div class="section">
    <div class="container">

      <div class="row">
        <div class="col-md-3">
          <div class="collapse-panel">
            <div class="card-body">
              <div class="card card-refine card-plain">
                <h4 class="card-title">
                  Affiner la recherche
                  <button class="btn btn-default btn-icon btn-neutral pull-right" rel="tooltip" title="Reset Filter">
                    <i class="arrows-1_refresh-69 now-ui-icons"></i>
                  </button>
                </h4>
                <div class="card-header" role="tab" id="headingOne">
                  <h6 class="mb-0">
                    <a data-toggle="collapse" data-parent="#accordion" href="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                      Fourchatte de prix
                      <i class="now-ui-icons arrows-1_minimal-down"></i>
                    </a>
                  </h6>
                </div>
                <div id="collapseOne" class="collapse show" role="tabpanel" aria-labelledby="headingOne">
                  <div class="card-body">
                    <span id="price-left" class="price-left pull-left" data-currency="&euro;">100</span>
                    <span id="price-right" class="price-right pull-right" data-currency="&euro;">850</span>
                    <div class="clearfix mb-2"></div>
                    <div id="sliderRefine" class="slider slider-refine"></div>
                  </div>
                </div>
              </div>
              <!-- Checkbox 'Marques' -->
              <div class="card card-refine card-plain">
                <div class="card-header" role="tab" id="headingTwo">
                  <h6 class="mb-0">
                    <a class="collapsed" data-toggle="collapse" data-parent="#accordion" href="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
                      Marque
                      <i class="now-ui-icons arrows-1_minimal-down"></i>
                    </a>
                  </h6>
                </div>
                <div id="collapseTwo" class="collapse" role="tabpanel" aria-labelledby="headingTwo">
                  <div class="card-body">
                    <div class="checkbox">
                      <input id="checkbox_brand" type="checkbox">
                      <label for="checkbox_brand">
                        Toutes <3
                      </label>
                    </div>
                    <!-- Boucle pour les marques -->
                    <% @products.each do |product| %>
                    <div class="checkbox">
                      <input id="checkbox_" type="checkbox">
                      <label for="checkbox_">
                        <%= product.brand %>
                      </label>
                    </div>
                    <% end %>
                    <!-- Fin de boucle -->
                  </div>
                </div>
              </div>
              <!-- Fin Checkbox 'Marques' -->
              <!-- Checkbox 'Catégories' -->
              <div class="card card-refine card-plain">
                <div class="card-header" role="tab" id="headingfour">
                  <h6 class="mb-0">
                    <a class="collapsed" data-toggle="collapse" data-parent="#accordion" href="#collapsefour" aria-expanded="false" aria-controls="collapsefour">
                      Cat-égories
                      <i class="now-ui-icons arrows-1_minimal-down"></i>
                    </a>
                  </h6>
                </div>
                <div id="collapsefour" class="collapse" role="tabpanel" aria-labelledby="headingfour">
                  <div class="card-body">
                    <div class="checkbox">
                      <input id="checkbox_cat" type="checkbox">
                      <label for="checkbox_cat">
                        Toutes
                      </label>
                    </div>
                    <% @categories.each do |category| %>
                    <div class="checkbox">
                      <input id="checkbox_<%=category.id%>" type="checkbox">
                      <label for="checkbox_<%=category.id%>">
                        <%= category.title %>
                      </label>
                    </div>
                    <% end %>
                  </div>
                </div>
              </div>
              <!-- Fin Checkbox 'Catégories' -->
            </div>
          </div>
        </div>



        <!-- Carte Produit -->
        <div class="col-md-9">
            <h1>ZONE ADMIN PRODUCTS INDEX</h1><br>
          <div class="row">
          <% @products.reverse.each do |product|%>
          <div class="col-lg-4 col-md-6">
            <div class="card card-product">
              <div class="card-image">
                <a href="/products/<%= product.id %>">

                  <%if product.image.attached?%>
                  <%= image_tag product.image, alt: 'image' %>
                  <%else%>
                  <img class="img rounded" src="https://static.wamiz.fr/images/animaux/chats/large/sphynx-2901.jpg" />
                  <%end%>


                </a>
              </div>
              <div class="card-body">
                <h6 class="category"><%= product.brand %></h6>
                <h5 class="card-title">
                  <div class="card-link "><%= product.title %></div>
                </h5>
                <div class="card-footer ">
                  <div class="price-container">
                    <span class="price "><%= product.price %>€</span>
                  </div>
                  <div class="row">
                    <span><%= button_to "changer l'image", admin_product_path(product), class: 'btn btn-neutral', method: :get %></span>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <% end%>
          </div>
        </div>

        <!-- Fin de la Carte Produit -->
      </div>
    </div>
  </div>
</div>

  <script type="text/javascript">
    $(document).ready(function() {

      var slider2 = document.getElementById('sliderRefine');

      noUiSlider.create(slider2, {
        start: [69, 666],
        connect: true,
        range: {
          'min': [30],
          'max': [900]
        }
      });

      var limitFieldMin = document.getElementById('price-left');
      var limitFieldMax = document.getElementById('price-right');

      slider2.noUiSlider.on('update', function(values, handle) {
        if (handle) {
          limitFieldMax.innerHTML = $('#price-right').data('currency') + Math.round(values[handle]);
        } else {
          limitFieldMin.innerHTML = $('#price-left').data('currency') + Math.round(values[handle]);
        }
      });
    });
  </script>

app/views/admin/products/new.html.erb
<h1>ZONE ADMIN PRODUCTS NEW</h1><br>
<h1>ZONE ADMIN PRODUCTS NEW</h1><br>

app/views/admin/products/show.html.erb
<h1>ZONE ADMIN PRODUCTS SHOW</h1><br>
<h1>ZONE ADMIN PRODUCTS SHOW</h1><br>
<main>
  <div class="wrapper">
    <div class="section">
      <div class="container">
        <a href="<%= admin_products_path %>"><i class="now-ui-icons arrows-1_minimal-left"></i> <span>Retour vers l'index</span></a>
        <div class="row">
          <div class="d-flex align-content-stretch flex-wrap">
            <div class="col-md-6 d-flex align-content-center flex-wrap">

              <%if @product.image.attached?%>
              <%= image_tag @product.image, alt: 'image' %>
              <%else%>
              <img class="d-block img-raised align-self-center" src="https://static.wamiz.fr/images/animaux/chats/large/sphynx-2942.jpg">
              <%end%>

            </div>
            <div class="col-md-5 ml-auto mr-auto">
              <h2 class="title"><%= @product.title %></h2>
              <h5 class="category"><%= @product.brand %> </h5>
              <h2 class="main-price"><%= @product.price %>€</h2>
              <%if @product.image.attached?%>
                <p>=== Il y a une image lié à ce produit ===</p>
                <%else%>
                <p>=== Il n'y a pas encore d'image lié à ce produit ===</p>
                <%end%>
                <h3>Changer d'image ?</h3>
                <%= form_tag admin_product_images_path(@product), multipart: true do %>
                <%= file_field_tag :image %>
                <%= submit_tag "changer l'image" %>
              <% end %>
              <div class="card-collapse">
                <div class="card card-plain">
                  <div class="card-header">
                    Description
                  </div>
                  <div class="card-body">
                    <p><%= @product.description %></p>
                    <% @all_cat_categories %>
                  </div>
                  <div class="card-header">
                    Reference : <%= @product.reference %>
                  </div>
                  <div class="card-header">
                    Categories :
                    <% @product.categories.each do |cat| %>
                    <span class="badge badge-neutral"><%= cat.title %></span>
                    <%end%>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="section related-products" data-background-color="black" >
      <div class="container">
        <h3 class="title text-center">You may also be interested in:</h3>
        <div class="row">
          <% @the_cats.sample(4).each do |product|%>

          <div class="col-sm-6 col-md-3">
            <div class="card card-product">
              <div class="card-image">
                <a href="/products/<%= product.id %>">
                  <img class="img rounded" src="https://static.wamiz.fr/images/animaux/chats/large/sphynx-2901.jpg" />
                </a>
              </div>
              <div class="card-body">
                <h6 class="category"><%= product.brand %></h6>
                <h5 class="card-title">
                  <div class="card-link "><%= product.title %></div>
                </h5>
                <div class="card-footer ">
                  <div class="price-container">
                    <span class="price "><%= product.price %>€</span>
                  </div>
                  <div class="row">
                    <span><%= button_to 'Voir le produit', product_path(product), class: 'btn btn-neutral', method: :get %></span>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <% end%>
          <!--  les anciennes cards fake avec les anciennes images

          <img class="img rounded" src="https://static.wamiz.fr/images/animaux/chats/large/sphynx-2903.jpg" />
          <img class="img rounded" src="http://www.totems-scouts.be/pics/totems/1394650360_sphynx.jpg" />
          <img class="img rounded" src="https://static.wamiz.fr/images/animaux/chats/large/sphynx-2902.jpg" />
        -->
      </div>
    </div>
  </div>
</div>
</main>