config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
  resources :users
  resources :products do
    resources :images, only: [:create]
  end
  root 'admin#index'
end


  root "products#index"
  get '/home/index'
  devise_for :users

  resources :line_items, only: [:create, :update, :destroy]
  resources :facturations, only: [:show, :index]
  resources :baskets, only: [:create, :update, :destroy, :show]
  resources :charges
  resources :categories, only: [:create, :update, :destroy, :show, :index]
  resources :products
end

app/models/line_item.rb
class LineItem < ApplicationRecord
  belongs_to :basket
  belongs_to :product
  default_scope { order('created_at DESC') }
end

app/controllers/line_items_controller.rb
class LineItemsController < ApplicationController
  include BasketsHelper
  before_action :set_line_item, only: [:show, :edit, :update, :destroy]

  # GET /line_items
  # GET /line_items.json
  def index
    @line_items = LineItem.all
  end

  # GET /line_items/1
  # GET /line_items/1.json
  def show
  end

  # GET /line_items/new
  def new
    @line_item = LineItem.new
  end

  # GET /line_items/1/edit
  def edit
  end

  # POST /line_items
  # POST /line_items.json
  def create
    product = Product.find(params[:product_id])
    @line_item = @current_basket.add_product(product)

    respond_to do |format|
      if @line_item.save
        format.html { redirect_to @line_item.basket, notice: 'Line item was successfully created.' }
        format.json { render :show, status: :created, location: @line_item }
      else
        format.html { render :new }
        format.json { render json: @line_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /line_items/1
  # PATCH/PUT /line_items/1.json
  def update
    @operator = params[:operator]
    respond_to do |format|
      if  @operator == "add"
        @line_item.update(:quantity => @line_item.quantity + 1 )
        @line_item_total = @line_item.product.price * @line_item.quantity.round(2)
        set_price
        format.html { redirect_to @line_item.basket, notice: 'Line item was successfully updated.' }
        format.js # { render :show, status: :ok, location: @line_item }
      elsif  @operator == "reduce"
        @line_item.update(:quantity => @line_item.quantity - 1)
        @line_item_total = @line_item.product.price * @line_item.quantity.round(2)
        set_price
        if @line_item.quantity == 0
          @line_item.destroy
        end
        format.html { redirect_to @line_item.basket, notice: 'Line item was successfully updated.' }
        format.js
      else
        format.html { render :edit }
        format.js
      end
    end
  end

  # DELETE /line_items/1
  # DELETE /line_items/1.json
  def destroy
    @line_item.destroy
    respond_to do |format|
      format.html { redirect_to @line_item.basket, notice: 'Line item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_line_item
      @line_item = LineItem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def line_item_params
      params.require(:line_item).permit(:basket_id, :product_id, :quantity)
    end
end

app/helpers/line_items_helper.rb
module LineItemsHelper

end

app/views/line_items/_form.html.erb
<%= form_with(model: line_item, local: true) do |form| %>
  <% if line_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(line_item.errors.count, "error") %> prohibited this line_item from being saved:</h2>

      <ul>
      <% line_item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :basket_id %>
    <%= form.text_field :basket_id %>
  </div>

  <div class="field">
    <%= form.label :product_id %>
    <%= form.text_field :product_id %>
  </div>

  <div class="field">
    <%= form.label :quantity %>
    <%= form.number_field :quantity %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/line_items/edit.html.erb
<h1>Editing Line Item</h1>

<%= render 'form', line_item: @line_item %>

<%= link_to 'Show', @line_item %> |
<%= link_to 'Back', line_items_path %>

app/views/line_items/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Line Items</h1>

<table>
  <thead>
    <tr>
      <th>Basket</th>
      <th>Product</th>
      <th>Quantity</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @line_items.each do |line_item| %>
      <tr>
        <td><%= line_item.basket %></td>
        <td><%= line_item.product %></td>
        <td><%= line_item.quantity %></td>
        <td><%= link_to 'Show', line_item %></td>
        <td><%= link_to 'Edit', edit_line_item_path(line_item) %></td>
        <td><%= link_to 'Destroy', line_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Line Item', new_line_item_path %>

app/views/line_items/new.html.erb
<h1>New Line Item</h1>

<%= render 'form', line_item: @line_item %>

<%= link_to 'Back', line_items_path %>

app/views/line_items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Basket:</strong>
  <%= @line_item.basket %>
</p>

<p>
  <strong>Product:</strong>
  <%= @line_item.product %>
</p>

<p>
  <strong>Quantity:</strong>
  <%= @line_item.quantity %>
</p>

<%= link_to 'Edit', edit_line_item_path(@line_item) %> |
<%= link_to 'Back', line_items_path %>

app/views/line_items/update.js.erb
console.log("bite")
console.log("<%= @price %>");

<% if @line_item.quantity == 0 %>
  $('#item_fulldiv_<%= @line_item.id %>').fadeOut('2000')
<% else %>
  $('#item_quantity_<%= @line_item.id%>').html("<%= @line_item.quantity %>")
  $('#item_total_<%= @line_item.id %>').html("<%= @line_item_total.round(2) %><small>€</small>")
<% end %>

$('#total_price').html("<%= @price %><small>€</small>")

<% if @price == 0 %>
  $('#checkout-btn').fadeOut('2000')
<% end %>